title: New Zealand
description: Our holiday to the New Zealand

url: http://stevenocchipinti.github.com
baseurl: "/2017-NewZealand-Blog"
paginate_path: page/
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

google_analytics: "UA-38345732-6"
